syntax = "proto3";

package exchange;

option go_package = "walletService/proto/exchange;exchange";

service ExchangeService {
  rpc GetExchangeRates(Empty) returns (ExchangeRatesResponse);
  rpc GetExchangeRateForCurrency(CurrencyRequest) returns (ExchangeRateResponse);
}

message Empty {}

message CurrencyRequest {
  string from_currency = 1;
  string to_currency = 2;
}

message ExchangeRateResponse {
  string from_currency = 1;
  string to_currency = 2;
  double rate = 3;
}

message ExchangeRatesResponse {
  map<string, double> rates = 1;
}
